/* 문제 분석
(1) 결과 컬럼 : WAREHOUSE_ID, WAREHOUSE_NAME,ADDRESS, FREEZER_YN
(2) 조회 기준 : 냉동시설 여부가 NULL인 경우 'N'으로, 
               경기도에 위치
(3) 아이디 기준으로 오름차순 : WAREHOUSE_ID
*/

SELECT WAREHOUSE_ID, 
       WAREHOUSE_NAME, 
       ADDRESS, 
       IF(FREEZER_YN IS NULL, 'N', FREEZER_YN) AS FREEZER_YN
FROM FOOD_WAREHOUSE 
WHERE WAREHOUSE_NAME LIKE '%_경기%'
ORDER BY WAREHOUSE_ID