/* 문제 분석
(1) 결과 컬럼 : MEMBER_ID, MEMBER_NAME, GENDER, DATE_OF_BIRTH
(2) 조회 기준 : 생일이 3월인 여성 회원,
               전화번호가 NULL인 경우는 출력대상에서 제외
(3) 아이디 기준으로 오름차순 : MEMBER_ID
*/

SELECT MEMBER_ID,
       MEMBER_NAME,
       GENDER,
       DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
# WHERE DATE_OF_BIRTH LIKE "%-03-%" AND TLNO IS NOT NULL AND GENDER = 'W'
WHERE MONTH(DATE_OF_BIRTH) = 3 AND TLNO IS NOT NULL AND GENDER = 'W'
ORDER BY MEMBER_ID