/* 문제 분석
(1) 결과 컬럼 : INGREDIENT_TYPE, TOTAL_ORDER
(2) 조회 기준 : 각 아이스크림 성분 타입에 대한 아이스크림의 총주문량
(3) 총주문량 기준으로 오름차순 : TOTAL_ORDER
*/

SELECT I.INGREDIENT_TYPE,
       SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF F
JOIN ICECREAM_INFO I
ON F.FLAVOR = I.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER