/* 문제 분석
(1) 결과 컬럼 : HOUR, COUNT
(2) 조회 기준 : 09:00부터 19:59까지, 각 시간대별로 입양이 몇 건이나 발생했는지
(3) 시간대 기준으로 오름차순 : HOUR
*/

SELECT HOUR(DATETIME) AS HOUR,
       COUNT(DATETIME) AS COUNT
FROM ANIMAL_OUTS
# WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR HAVING HOUR BETWEEN 9 AND 19
ORDER BY HOUR


# SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR,
#        COUNT(DATE_FORMAT(DATETIME, '%H')) AS COUNT
# FROM ANIMAL_OUTS
# GROUP BY HOUR HAVING HOUR BETWEEN 9 AND 19
# ORDER BY HOUR