/* 문제 분석
(1) 결과 컬럼 : CATEGORY, PRODUCTS
(2) 조회 기준 : 상품 카테고리 코드(PRODUCT_CODE 앞 2자리) 별 상품 개수
(3) 아이디 기준으로 오름차순 : ANIMAL_ID
*/

SELECT SUBSTRING(PRODUCT_CODE, 1, 2) AS CATEGORY,
       COUNT(*) AS PRODUCTS
FROM PRODUCT 
GROUP BY CATEGORY
ORDER BY CATEGORY

# SELECT LEFT(PRODUCT_CODE, 2) AS CATEGORY,
#        COUNT(*) AS PRODUCTS
# FROM PRODUCT 
# GROUP BY CATEGORY
# ORDER BY CATEGORY